### ISSUE TITLE
FontAwesome styles are loaded twice on vcl.github.io

### ISSUE THREAD

**Issue by OrKoN** [vcl/doc#9]
![selection_142](https://cloud.githubusercontent.com/assets/399150/10262839/e6528626-69d8-11e5-91a5-dcedffd7724a.png)

**Comment by vanthome** [comment]
This is because we have the vcl integration module in the CSS and additionally load the CSS from a CDN with this `<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">`. I will remove the integration lib as it is not necessary.

**Comment by vanthome** [comment]
Solved via https://github.com/vcl/doc-client/commit/4fcd9675e8e3394be7b3e08424c13e94f12dbe0a
